export const dictionary = {
    'Россия' : 'Russia',
    'США' : 'USA',
    'Мир' : 'World',
    'Индия:' : "India", 
    'Бразилия:' : "Brazil",
    'Франция:' : "France",
    'Испания:' : "Spain", 
    'Великобритания:' : "UK",
    'Италия:' : "Italy", 
    'Аргентина:' : "Argentina",
    'Колумбия': "Colombia",
    'Мексика': "Mexico",
    'Перу': "Peru",
    'Германия': "Germany",
    'Польша': "Poland",
    'Иран': "Iran",
    'Южная Африка': "South Africa",
    'Украина': "Ukraine",
    'Бельгия': "Belgium",
    'Чили': "Chile",
    'Ирак': "Iraq",
    'Чехия': "Czechia",
    'Недерланды': "Netherlands",
    'Турция': "Turkey",
    'Бангладеш': "Bangladesh",
    'Румыния': "Romania",
    'Филиппины': "Philippines", 
    'Пакистан': "Pakistan", 
    'Саудовская Аравия': "Saudi Arabia",
    'Канада': "Canada", 
    'Израиль': "Israel",
    'Марокко': "Morocco", 
    'Швейцария': "Switzerland",
    'Португалия': "Portugal", 
    'Австрия': "Austria",
    'Швеция': "Sweden",
    'Непал': "Nepal",
    'Иордания': "Jordan",
    'Эквадор': "Ecuador", 
    'Венгрия': "Hungary", 
    'ОАЭ': "UAE",
    'Панама': "Panama", 
    'Боливия': "Bolivia", 
    'Кувейт': "Kuwait", 
    'Доминиканская Республика': "Dominican Republic",
    'Катар': "Qatar",
    'Япония': "Japan", 
    'Коста-Рика': "Costa Rica",  
    'Армения': "Armenia", 
    'Беларусь': "Belarus", 
    'Казахстан': "Kazakhstan", 
    'Сербия': "Serbia", 
    'Болгария': "Bulgaria", 
    'Оман': "Oman", 
    'Гватемала': "Guatemala",
    'Ливан': "Lebanon",
    'Египет': "Egypt",
    'Грузия': "Georgia", 
    'Хорватия': "Croatia",
    'Эфиопия': "Ethiopia",
    'Гондурас': "Honduras", 
    'Венесуэла': "Venezuela",
    'Азербайджан': "Azerbaijan",
    'Молдова': "Moldova",
    'Словакия': "Slovakia", 
    'Греция': "Greece",
    'Тунис': "Tunisia", 
    'Бахрейн': "Bahrain", 
    'Мьянма': "Myanmar",
    'Босния и Герцеговина': "Bosnia and Herzegovina",
    'Ливия': "Libya",
    'Кения': "Kenya",
    'Парагвай': "Paraguay",
    'Алжир': "Algeria",
    'Палестина': "Palestine",
    'Дания': "Denmark",
    'Узбекистан': "Uzbekistan",
    'Ирландия': "Ireland", 
    'Кыргызстан': "Kyrgyzstan", 
    'Словения': "Slovenia",
    'Нигерия': "Nigeria", 
    'Малайзия': "Malaysia", 
    'Сингапур': "Singapore", 
    'Северная Македония': "North Macedonia",
    'Гана': "Ghana",
    'Литва': "Lithuania", 
    'Афганистан': "Afghanistan",
    'Сальвадор': "El Salvador", 
    'Албания': "Albania",
    'Норвегия': "Norway", 
    'Черногория': "Montenegro", 
    'Южная Корея': "S. Korea",
    'Люксембург': "Luxembourg", 
    'Австралия': "Australia", 
    'Камерун': "Cameroon",
    'Финляндия': "Finland",  
    "Кот-д'Ивуар": "Ivory Coast", 
    'Шри-Ланка': "Sri Lanka",
    'Уганда' : "Uganda",
    'Замбия': "Zambia",
    'Мадагаскар' : "Madagascar", 
    'Судан' : "Sudan", 
    'Сенегал' : "Senegal",
    'Мозамбик' : "Mozambique", 
    'Ангола' : "Angola",
    'Намибия' : "Namibia", 
    'Латвия' : "Latvia", 
    'Французская Полинезия' : "French Polynesia",
    'Гвинея' : "Guinea", 
    'Мальдивы' : "Maldives",
    'ДРК' : "DRC", 
    'Таджикистан' : "Tajikistan", 
    'Французская Гвиана' : "French Guiana",
    'Ямайка' : "Jamaica", 
    'Кабо-Верде' : "Cabo Verde", 
    'Эстония' : "Estonia", 
    'Ботсвана' : "Botswana", 
    'Зимбабве' : "Zimbabwe", 
    'Гаити' : "Haiti", 
    'Габон' : "Gabon", 
    'Мальта' : "Malta", 
    'Кипр' : "Cyprus",
    'Гваделупа' : "Guadeloupe", 
    'Мавритания' : "Mauritania", 
    'Куба' : "Cuba",
    'Реюньон' : "Réunion", 
    'Багамы' : "Bahamas", 
    'Сирия' : "Syria", 
    'Тринидад и Тобаго' : "Trinidad and Tobago",
    'Андорра' : "Andorra", 
    'Эсватини' : "Eswatini",
    'Малави' : "Malawi",
    'Гонконг' : "Hong Kong",
    'Руанда' : "Rwanda", 
    'Никарагуа' : "Nicaragua",
    'Джибути' : "Djibouti", 
    'Конго' : "Congo", 
    'Исландия' : "Iceland", 
    'Суринам' : "Suriname",
    'Белиз' : "Belize", 
    'Гайана' : "Guyana", 
    'Экваториальная Гвинея' : "Equatorial Guinea", 
    'Майотта' : "Mayotte",
    'Центральноафриканская Республика' : "Central African Republic",
    'Уругвай' : "Uruguay", 
    'Аруба' : "Aruba",
    'Мартиника' : "Martinique", 
    'Сомали' : "Somalia", 
    'Мали' : "Mali", 
    'Тайланд' : "Thailand", 
    'Гамбия' : "Gambia", 
    'Южный Судан' : "South Sudan",
    'Бенин' : "Benin", 
    'Того' : "Togo", 
    'Буркина-Фасо' : "Burkina Faso", 
    'Гвинея-Бисау' : "Guinea-Bissau", 
    'Сьерра-Леоне' : "Sierra Leone", 
    'Йемен' : "Yemen", 
    'Лесото' : "Lesotho", 
    'Новая Зеландия' : "New Zealand", 
    'Кюрасао' : "Curaçao", 
    'Чад' : "Chad", 
    'Либерия' : "Liberia", 
    'Сан-Марино' : "San Marino",  
    'Нигер' : "Niger", 
    'Вьетнам' : "Vietnam", 
    'Лихтенштейн' : "Liechtenstein", 
    'Нормандские острова' : "Channel Islands", 
    'Синт-Мартен' : "Sint Maarten", 
    'Сан-Томе и Принсипи' : "Sao Tome and Principe",
    'Гибралтар' : "Gibraltar", 
    'Теркс и Кайкос' : "Turks and Caicos", 
    'Алмазная принцесса' : "Diamond Princess", 
    'Сен-Мартен' : "Saint Martin", 
    'Монголия' : "Mongolia",
    'Бурунди' : "Burundi",
    'Папуа - Новая Гвинея' : "Papua New Guinea", 
    'Тайван' : "Taiwan",
    'Коморские острова' : "Comoros",
    'Монако' : "Monaco",
    'Эритрея' : "Eritrea",
    'Танзания' : "Tanzania",
    'Фарерские острова' : "Faeroe Islands",
    'Маврикий' : "Mauritius", 
    'Бутан' : "Bhutan", 
    'Остров Мэн' : "Isle of Man",
    'Камбоджа' : "Cambodia", 
    'Каймановы острова' : "Cayman Islands",
    'Барбадос' : "Barbados", 
    'Бермуды' : "Bermuda",
    'Санкт-Люсия' : "Saint Lucia",
    'Сейшельские острова' : "Seychelles",
    'Карибские Нидерланды' : "Caribbean Netherlands", 
    'Бруней' : "Brunei",  
    'Антигуа и Барбуда' : "Antigua and Barbuda", 
    'Сен-Барт' : "St. Barth", 
    'Сент-Винсент Гренадины' : "St. Vincent Grenadines",
    'Доминика' : "Dominica",
    'Британские Виргинские острова' : "British Virgin Islands",
    'Макао' : "Macao", 
    'Гренада' : "Grenada", 
    'Лаос' : "Laos", 
    'Фиджи' : "Fiji",
    'Новая Каледония' : "New Caledonia", 
    'Тимор-Лешти' : "Timor-Leste",
    'Ватикан' : "Vatican City", 
    'Сент-Китс и Невис' : "Saint Kitts and Nevis", 
    'Гренландия' : "Greenland", 
    'Фолклендские острова' : "Falkland Islands", 
    'Сен-Пьер Микелон' : "Saint Pierre Miquelon", 
    'Соломоновы острова' : "Solomon Islands",
    'Монсеррат' : "Montserrat", 
    'Западная Сахара' : "Western Sahara", 
    'МС Заандам' : "MS Zaandam",
    'Ангилья' : "Anguilla", 
    'Маршалловы острова' : "Marshall Islands", 
    'Уоллис и Футуна' : "Wallis and Futuna", 
    'Самоа' : "Samoa", 
    'Вануату' : "Vanuatu", 
    'Китай' : "China"
}
